//
// Created by Keiwan Jamaly on 02.12.22.
//

#ifndef SIMULATION_GLOBAL_INCLUDE_H
#define SIMULATION_GLOBAL_INCLUDE_H

#define BOOST_ALLOW_DEPRECATED_HEADERS
#define BOOST_BIND_GLOBAL_PLACEHOLDERS

#endif //SIMULATION_GLOBAL_INCLUDE_H
